/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from '../../app.constants';

export const listItemRoutes: Routes = [
	{ loadComponent: () => import('./list-item.docs').then(m => m.ListItemDocsComponent), path: '' },
	{ loadComponent: () => import('./account-clickthrough-list/account-clickthrough-list.docs').then(m => m.AccountClickthroughListComponent), path: 'account-clickthrough-list', title: 'Account clickthrough list list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./checkbox-list/checkbox-list.docs').then(m => m.CheckboxListComponent), path: 'checkbox-list', title: 'Checkbox list list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./clickthrough-list/clickthrough-list.docs').then(m => m.ClickthroughListComponent), path: 'clickthrough-list', title: 'Clickthrough list list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default-checkbox/default-checkbox.docs').then(m => m.DefaultCheckboxListItemComponent), path: 'default-checkbox', title: 'Default checkbox list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default-clickthrough/default-clickthrough.docs').then(m => m.DefaultClickthroughListItemComponent), path: 'default-clickthrough', title: 'Default clickthrough list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default-list/default-list.docs').then(m => m.DefaultListComponent), path: 'default-list', title: 'Default list list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default-list-with-dividers/default-list-with-dividers.docs').then(m => m.DefaultListWithDividersComponent), path: 'default-list-with-dividers', title: 'Default list with dividers list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default-list-with-section-title-and-hyperlink/default-list-with-section-title-and-hyperlink.docs').then(m => m.DefaultListWithSectionTitleAndHyperlinkComponent), path: 'default-list-with-section-title-and-hyperlink', title: 'Default list with section title and hyperlink list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default-list-with-title/default-list-with-title.docs').then(m => m.DefaultListWithTitleComponent), path: 'default-list-with-title', title: 'Default list with title list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default-radio/default-radio.docs').then(m => m.DefaultRadioListItemComponent), path: 'default-radio', title: 'Default radio list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default-switch/default-switch.docs').then(m => m.DefaultSwitchListItemComponent), path: 'default-switch', title: 'Default switch list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled-card-art-clickthrough/disabled-card-art-clickthrough.docs').then(m => m.DisabledCardArtClickthroughListItemComponent), path: 'disabled-card-art-clickthrough', title: 'Disabled card art clickthrough list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled-card-art-with-number-clickthrough/disabled-card-art-with-number-clickthrough.docs').then(m => m.DisabledCardArtWithNumberClickthroughListItemComponent), path: 'disabled-card-art-with-number-clickthrough', title: 'Disabled card art with number clickthrough list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled-checkbox/disabled-checkbox.docs').then(m => m.DisabledCheckboxListItemComponent), path: 'disabled-checkbox', title: 'Disabled checkbox list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled-clickthrough/disabled-clickthrough.docs').then(m => m.DisabledClickthroughListItemComponent), path: 'disabled-clickthrough', title: 'Disabled clickthrough list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled-leading-icon-clickthrough/disabled-leading-icon-clickthrough.docs').then(m => m.DisabledLeadingIconClickthroughListItemComponent), path: 'disabled-leading-icon-clickthrough', title: 'Disabled leading icon clickthrough list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled-leading-image-clickthrough/disabled-leading-image-clickthrough.docs').then(m => m.DisabledLeadingImageClickthroughListItemComponent), path: 'disabled-leading-image-clickthrough', title: 'Disabled leading image clickthrough list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled-radio/disabled-radio.docs').then(m => m.DisabledRadioListItemComponent), path: 'disabled-radio', title: 'Disabled radio list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled-switch/disabled-switch.docs').then(m => m.DisabledSwitchListItemComponent), path: 'disabled-switch', title: 'Disabled switch list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./indicator-line/indicator-line.docs').then(m => m.IndicatorLineListItemComponent), path: 'indicator-line', title: 'Indicator line list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./leading-card-art/leading-card-art.docs').then(m => m.LeadingCardArtListItemComponent), path: 'leading-card-art', title: 'Leading card art list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./leading-icon/leading-icon.docs').then(m => m.LeadingIconListItemComponent), path: 'leading-icon', title: 'Leading icon list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./leading-icon-with-background/leading-icon-with-background.docs').then(m => m.LeadingIconWithBackgroundListItemComponent), path: 'leading-icon-with-background', title: 'Leading icon with background list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./leading-image/leading-image.docs').then(m => m.LeadingImageListItemComponent), path: 'leading-image', title: 'Leading image list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./one-line/one-line.docs').then(m => m.OneLineListItemComponent), path: 'one-line', title: 'One line list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./one-line-two-column/one-line-two-column.docs').then(m => m.OneLineTwoColumnListItemComponent), path: 'one-line-two-column', title: 'One line two column list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./radio-list/radio-list.docs').then(m => m.RadioListComponent), path: 'radio-list', title: 'Radio list list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./three-line/three-line.docs').then(m => m.ThreeLineListItemComponent), path: 'three-line', title: 'Three line list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./trailing-card-art/trailing-card-art.docs').then(m => m.TrailingCardArtListItemComponent), path: 'trailing-card-art', title: 'Trailing card art list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./trailing-icon/trailing-icon.docs').then(m => m.TrailingIconListItemComponent), path: 'trailing-icon', title: 'Trailing icon list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./trailing-icon-with-background/trailing-icon-with-background.docs').then(m => m.TrailingIconWithBackgroundListItemComponent), path: 'trailing-icon-with-background', title: 'Trailing icon with background list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./trailing-image/trailing-image.docs').then(m => m.TrailingImageListItemComponent), path: 'trailing-image', title: 'Trailing image list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./transactions-list/transactions-list.docs').then(m => m.TransactionsListComponent), path: 'transactions-list', title: 'Transactions list list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./two-line/two-line.docs').then(m => m.TwoLineListItemComponent), path: 'two-line', title: 'Two line list item component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default listItemRoutes;