/**
 *              © 2025-2026 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from '../../app.constants';

export const testsRoutes: Routes = [
	{ loadComponent: () => import('./tests.docs').then(m => m.TestDocsComponent), path: '' },
	{ loadComponent: () => import('./combobox-focus-test/combobox-focus-test.docs').then(m => m.ComboboxFocusTestComponent), path: 'combobox-focus-test', title: 'Combobox focus test tests component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./combobox-in-dialog-tab-panel/test.docs').then(m => m.ComboboxFocusTestComponent), path: 'test', title: 'Test tests component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./floating-ui-in-disclosure-tab/floating-ui-in-disclosure-tab.docs').then(m => m.FloatingUiInDisclosureTabTestComponent), path: 'floating-ui-in-disclosure-tab', title: 'Floating ui in disclosure tab tests component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./floating-ui-in-panel/floating-ui-in-panel.docs').then(m => m.FloatingUiInPanelTestComponent), path: 'floating-ui-in-panel', title: 'Floating ui in panel tests component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./form-control-ng/form-control-ng.docs').then(m => m.FormControlNgComponent), path: 'form-control-ng', title: 'Form control ng tests component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./form-control-values/form-control-values.docs').then(m => m.FormControlValuesComponent), path: 'form-control-values', title: 'Form control values tests component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./horizontal-nav-nested-menus/horizontal-nav-nested-menus.docs').then(m => m.HorizontalNavNestedMenusTestComponent), path: 'horizontal-nav-nested-menus', title: 'Horizontal nav nested menus tests component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nested-accordions/nested-accordions.docs').then(m => m.NestedAccordionsTestComponent), path: 'nested-accordions', title: 'Nested accordions tests component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nested-combobox-in-dropdown/nested-combobox-in-dropdown.docs').then(m => m.NestedComboboxInDropdownTestComponent), path: 'nested-combobox-in-dropdown', title: 'Nested combobox in dropdown tests component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nested-floating-elements/nested-floating-elements.docs').then(m => m.NestedFloatingElementsTestComponent), path: 'nested-floating-elements', title: 'Nested floating elements tests component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nested-menus/nested-menus.docs').then(m => m.NestedMenusTestComponent), path: 'nested-menus', title: 'Nested menus tests component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nested-triggers/nested-triggers.docs').then(m => m.NestedTriggersTestComponent), path: 'nested-triggers', title: 'Nested triggers tests component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./using-toggle-icon-directive/using-toggle-icon-directive.docs').then(m => m.UsingToggleIconDirectiveComponent), path: 'using-toggle-icon-directive', title: 'Using toggle icon directive tests component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default testsRoutes;