/**
 *              © 2025-2026 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from '../../app.constants';

export const chatRoutes: Routes = [
	{ loadComponent: () => import('./chat.docs').then(m => m.ChatDocsComponent), path: '' },
	{ loadComponent: () => import('./dialog-chat/dialog-chat.docs').then(m => m.DialogChatComponent), path: 'dialog-chat', title: 'Dialog chat chat pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./full-page-chat/full-page-chat.docs').then(m => m.FullPageChatComponent), path: 'full-page-chat', title: 'Full page chat chat pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./panel-chat/panel-chat.docs').then(m => m.PanelChatComponent), path: 'panel-chat', title: 'Panel chat chat pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/chat-actions/chat-actions.docs').then(m => m.ChatActionsComponent), path: 'chat-actions', title: 'Chat actions chat pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/chat-code-snippet-single/chat-code-snippet-single.docs').then(m => m.ChatCodeSnippetSingleComponent), path: 'chat-code-snippet-single', title: 'Chat code snippet single chat pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/chat-input/chat-input.docs').then(m => m.ChatInputComponent), path: 'chat-input', title: 'Chat input chat pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/chat-suggestions/chat-suggestions.docs').then(m => m.ChatSuggestionsComponent), path: 'chat-suggestions', title: 'Chat suggestions chat pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/full-page-navigation/full-page-navigation.docs').then(m => m.FullPageNavigationComponent), path: 'full-page-navigation', title: 'Full page navigation chat pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/response-chat-bubble/response-chat-bubble.docs').then(m => m.ResponseChatBubbleComponent), path: 'response-chat-bubble', title: 'Response chat bubble chat pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/user-chat-bubble/user-chat-bubble.docs').then(m => m.UserChatBubbleComponent), path: 'user-chat-bubble', title: 'User chat bubble chat pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default chatRoutes;