/**
 *              © 2025-2026 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from '../../app.constants';

export const dynamicTableRoutes: Routes = [
	{ loadComponent: () => import('./dynamic-table.docs').then(m => m.DynamicTableDocsComponent), path: '' },
	{ loadComponent: () => import('./action-bar-and-pagination/action-bar-and-pagination.docs').then(m => m.ActionBarAndPaginationDynamicTableComponent), path: 'action-bar-and-pagination', title: 'Action bar and pagination dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./column-header-actions/edit-action/edit-action.docs').then(m => m.EditActionDynamicTableComponent), path: 'edit-action', title: 'Edit action dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./column-header-actions/column-header-actions.docs').then(m => m.ColumnHeaderActionsDynamicTableComponent), path: 'column-header-actions', title: 'Column header actions dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./data-fetch-on-accordion-toggle/data-fetch-on-accordion-toggle.docs').then(m => m.DataFetchAccordionToggleDynamicTableComponent), path: 'data-fetch-on-accordion-toggle', title: 'Data fetch on accordion toggle dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./data-fetch-on-pagination/data-fetch-on-pagination.docs').then(m => m.DataFetchOnPaginationDynamicTableComponent), path: 'data-fetch-on-pagination', title: 'Data fetch on pagination dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default/default.docs').then(m => m.DefaultDynamicTableComponent), path: 'default', title: 'Default dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./filter-dialog/filter-dialog.docs').then(m => m.FilterDialogDynamicTableComponent), path: 'filter-dialog', title: 'Filter dialog dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./filters/filters.docs').then(m => m.FiltersDynamicTableComponent), path: 'filters', title: 'Filters dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./in-table-filters/in-table-filters.docs').then(m => m.InTableFiltersDynamicTableComponent), path: 'in-table-filters', title: 'In table filters dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./indeterminate-circular-progress/indeterminate-circular-progress.docs').then(m => m.IndeterminateCircularProgressDynamicTableComponent), path: 'indeterminate-circular-progress', title: 'Indeterminate circular progress dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./indeterminate-linear-progress/indeterminate-linear-progress.docs').then(m => m.IndeterminateLinearProgressDynamicTableComponent), path: 'indeterminate-linear-progress', title: 'Indeterminate linear progress dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multi-row-expandable/multi-row-expandable.docs').then(m => m.MultiRowExpandableDynamicTableComponent), path: 'multi-row-expandable', title: 'Multi row expandable dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multi-select/multi-select.docs').then(m => m.MultiSelectDynamicTableComponent), path: 'multi-select', title: 'Multi select dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multiple-action-buttons/multiple-action-buttons.docs').then(m => m.MultipleActionButtonsDynamicTableComponent), path: 'multiple-action-buttons', title: 'Multiple action buttons dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./notifications/notification-indicator/notification-indicator.docs').then(m => m.NotificationIndicatorComponent), path: 'notification-indicator', title: 'Notification indicator dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./notifications/notifications.docs').then(m => m.NotificationsDynamicTableComponent), path: 'notifications', title: 'Notifications dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./pagination/pagination.docs').then(m => m.PaginationDynamicTableComponent), path: 'pagination', title: 'Pagination dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./pinned-column-and-horizontal-scroll/pinned-column-and-horizontal-scroll.docs').then(m => m.PinnedColumnAndHorizontalScrollDynamicTableComponent), path: 'pinned-column-and-horizontal-scroll', title: 'Pinned column and horizontal scroll dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./search-action-bar/search-action-bar.docs').then(m => m.SearchActionBarDynamicTableComponent), path: 'search-action-bar', title: 'Search action bar dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./selection-based-action-bar/selection-based-action-bar.docs').then(m => m.SelectionBasedActionBarDynamicTableComponent), path: 'selection-based-action-bar', title: 'Selection based action bar dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/action-bar/action-bar.docs').then(m => m.SharedActionBarDynamicTableComponent), path: 'action-bar', title: 'Action bar dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/actions-button/actions-button.docs').then(m => m.ActionsButtonDynamicTableComponent), path: 'actions-button', title: 'Actions button dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/badge/shared-badge.docs').then(m => m.SharedBadgeDynamicTableComponent), path: 'shared-badge', title: 'Shared badge dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/expandable-filter-dropdown/expandable-filter-dropdown.docs').then(m => m.ExpandableFilterDropdownDynamicTableComponent), path: 'expandable-filter-dropdown', title: 'Expandable filter dropdown dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/filter-checkbox-lists/filter-checkbox-lists.docs').then(m => m.FilterCheckboxListsDynamicTable), path: 'filter-checkbox-lists', title: 'Filter checkbox lists dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/filter-chips/filter-chips.docs').then(m => m.SharedFilterChipsDynamicTableComponent), path: 'filter-chips', title: 'Filter chips dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/pagination/shared-pagination.docs').then(m => m.SharedPaginationDynamicTableComponent), path: 'shared-pagination', title: 'Shared pagination dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/show-columns-dropdown/show-columns-dropdown.docs').then(m => m.ShowColumnsDropdownDynamicTableComponent), path: 'show-columns-dropdown', title: 'Show columns dropdown dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/sort-icon/sort-icon.docs').then(m => m.SharedSortIconDynamicTableComponent), path: 'sort-icon', title: 'Sort icon dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./single-row-expandable/single-row-expandable.docs').then(m => m.SingleRowExpandableDynamicTableComponent), path: 'single-row-expandable', title: 'Single row expandable dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./subtle-action-bar/subtle-action-bar.docs').then(m => m.SubtleActionBarDynamicTableComponent), path: 'subtle-action-bar', title: 'Subtle action bar dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./toggle-action-bar/toggle-action-bar.docs').then(m => m.ToggleActionBarDynamicTableComponent), path: 'toggle-action-bar', title: 'Toggle action bar dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./vertical-and-horizontal-scroll/vertical-and-horizontal-scroll.docs').then(m => m.VerticalAndHorizontalScrollDynamicTableComponent), path: 'vertical-and-horizontal-scroll', title: 'Vertical and horizontal scroll dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./vertical-scroll-and-sticky-row/vertical-scroll-and-sticky-row.docs').then(m => m.VerticalScrollAndStickyRowDynamicTableComponent), path: 'vertical-scroll-and-sticky-row', title: 'Vertical scroll and sticky row dynamic table pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default dynamicTableRoutes;