/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from '../../app.constants';

export const applicationLayoutsRoutes: Routes = [
  { loadComponent: () => import('./application-layouts.docs').then((m) => m.ApplicationLayoutsDocsComponent), path: '' },
  {
    loadComponent: () => import('./horizontal-application-layout/horizontal-application-layout.docs').then((m) => m.HorizontalApplicationLayoutComponent),
    path: 'horizontal-application-layout',
    title: 'Horizontal Application Layout | Example' + TITLE_SEPARATOR + TITLE_SUFFIX
  },
  {
    loadComponent: () => import('./stacked-horizontal-application-layout/stacked-horizontal-application-layout.docs').then((m) => m.StackedHorizontalApplicationLayoutComponent),
    path: 'stacked-horizontal-application-layout',
    title: 'Stacked Horizontal Application Layout | Example' + TITLE_SEPARATOR + TITLE_SUFFIX
  },
  {
    loadComponent: () => import('./vertical-application-layout/vertical-application-layout.docs').then((m) => m.VerticalApplicationLayoutComponent),
    path: 'vertical-application-layout',
    title: 'Vertical Application Layout | Example' + TITLE_SEPARATOR + TITLE_SUFFIX
  },
  {
    loadComponent: () => import('./mixed-application-layout/mixed-application-layout.docs').then((m) => m.MixedApplicationLayoutComponent),
    path: 'mixed-application-layout',
    title: 'Mixed Application Layout | Example' + TITLE_SEPARATOR + TITLE_SUFFIX
  }
];

export default applicationLayoutsRoutes;