/**
 *              © 2025-2026 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from '../../app.constants';

export const fileUploadRoutes: Routes = [
	{ loadComponent: () => import('./file-upload.docs').then(m => m.FileUploadDocsComponent), path: '' },
	{ loadComponent: () => import('./file-upload-with-alternate-display/file-upload-with-alternate-display.docs').then(m => m.FileUploadWithAlternateDisplayComponent), path: 'file-upload-with-alternate-display', title: 'File upload with alternate display file upload pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multi-file-manual-upload/multi-file-manual-upload.docs').then(m => m.MultiFileManualUploadComponent), path: 'multi-file-manual-upload', title: 'Multi file manual upload file upload pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multi-file-upload/multi-file-upload.docs').then(m => m.MultiFileUploadComponent), path: 'multi-file-upload', title: 'Multi file upload file upload pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/sort-button/sort-button.docs').then(m => m.SharedSortButtonComponent), path: 'sort-button', title: 'Sort button file upload pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/upload-card/upload-card.docs').then(m => m.UploadCardComponent), path: 'upload-card', title: 'Upload card file upload pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/upload-dialog/upload-dialog.docs').then(m => m.UploadDialogComponent), path: 'upload-dialog', title: 'Upload dialog file upload pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/upload-row/upload-row.docs').then(m => m.UploadRowComponent), path: 'upload-row', title: 'Upload row file upload pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shared/upload-success-flag/upload-success-flag.docs').then(m => m.UploadSuccessFlagComponent), path: 'upload-success-flag', title: 'Upload success flag file upload pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./single-file-upload/single-file-upload.docs').then(m => m.SingleFileUploadComponent), path: 'single-file-upload', title: 'Single file upload file upload pattern | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default fileUploadRoutes;